mkdir -p ./analysis_results

cp -ar analysis_results_backup/lfs_dir_close#16     ./analysis_results/lfs_dir_close#16 
cp -ar analysis_results_backup/lfs_dir_drop#22  ./analysis_results/lfs_dir_drop#22 
cp -ar analysis_results_backup/lfs_dir_getinfo#27   ./analysis_results/lfs_dir_getinfo#27 
cp -ar analysis_results_backup/lfs_dir_open#31  ./analysis_results/lfs_dir_open#31 
cp -ar analysis_results_backup/lfs_dir_open_#32     ./analysis_results/lfs_dir_open_#32 
cp -ar analysis_results_backup/lfs_dir_read#34  ./analysis_results/lfs_dir_read#34 
cp -ar analysis_results_backup/lfs_dir_read_#35     ./analysis_results/lfs_dir_read_#35 
cp -ar analysis_results_backup/lfs_dir_rewind#37    ./analysis_results/lfs_dir_rewind#37 
cp -ar analysis_results_backup/lfs_dir_seek#39  ./analysis_results/lfs_dir_seek#39 
cp -ar analysis_results_backup/lfs_dir_seek_#40     ./analysis_results/lfs_dir_seek_#40 
cp -ar analysis_results_backup/lfs_dir_split#41     ./analysis_results/lfs_dir_split#41 
cp -ar analysis_results_backup/lfs_dir_tell#43  ./analysis_results/lfs_dir_tell#43 
cp -ar analysis_results_backup/lfs_file_opencfg#52  ./analysis_results/lfs_file_opencfg#52 
cp -ar analysis_results_backup/lfs_file_rewind#58   ./analysis_results/lfs_file_rewind#58 
cp -ar analysis_results_backup/lfs_file_seek#59     ./analysis_results/lfs_file_seek#59 
cp -ar analysis_results_backup/lfs_file_seek_#60    ./analysis_results/lfs_file_seek_#60 
cp -ar analysis_results_backup/lfs_file_size#61     ./analysis_results/lfs_file_size#61 
cp -ar analysis_results_backup/lfs_file_size_#62    ./analysis_results/lfs_file_size_#62 
cp -ar analysis_results_backup/lfs_file_sync#63     ./analysis_results/lfs_file_sync#63 
cp -ar analysis_results_backup/lfs_file_tell#65     ./analysis_results/lfs_file_tell#65 
cp -ar analysis_results_backup/lfs_file_truncate#66     ./analysis_results/lfs_file_truncate#66 
cp -ar analysis_results_backup/lfs_file_truncate_#67    ./analysis_results/lfs_file_truncate_#67 
cp -ar analysis_results_backup/lfs_format#70    ./analysis_results/lfs_format#70 
cp -ar analysis_results_backup/lfs_fs_deorphan#73   ./analysis_results/lfs_fs_deorphan#73 
cp -ar analysis_results_backup/lfs_fs_grow#79   ./analysis_results/lfs_fs_grow#79 
cp -ar analysis_results_backup/lfs_fs_mkconsistent#81   ./analysis_results/lfs_fs_mkconsistent#81 
cp -ar analysis_results_backup/lfs_fs_mkconsistent_#82  ./analysis_results/lfs_fs_mkconsistent_#82 
cp -ar analysis_results_backup/lfs_fs_parent#83     ./analysis_results/lfs_fs_parent#83 
cp -ar analysis_results_backup/lfs_fs_parent_match#84   ./analysis_results/lfs_fs_parent_match#84 
cp -ar analysis_results_backup/lfs_fs_pred#85   ./analysis_results/lfs_fs_pred#85 
cp -ar analysis_results_backup/lfs_fs_size#86   ./analysis_results/lfs_fs_size#86 
cp -ar analysis_results_backup/lfs_fs_stat#87   ./analysis_results/lfs_fs_stat#87 
cp -ar analysis_results_backup/lfs_fs_stat_#88  ./analysis_results/lfs_fs_stat_#88 
cp -ar analysis_results_backup/lfs_getattr#91   ./analysis_results/lfs_getattr#91 
cp -ar analysis_results_backup/lfs_getattr_#92  ./analysis_results/lfs_getattr_#92 
cp -ar analysis_results_backup/lfs_remove#99    ./analysis_results/lfs_remove#99 
cp -ar analysis_results_backup/lfs_remove_#100  ./analysis_results/lfs_remove_#100 
cp -ar analysis_results_backup/lfs_removeattr#101   ./analysis_results/lfs_removeattr#101 
cp -ar analysis_results_backup/lfs_rename#102   ./analysis_results/lfs_rename#102 
cp -ar analysis_results_backup/lfs_rename_#103  ./analysis_results/lfs_rename_#103 
cp -ar analysis_results_backup/lfs_setattr#104  ./analysis_results/lfs_setattr#104 
cp -ar analysis_results_backup/lfs_stat#105     ./analysis_results/lfs_stat#105 
cp -ar analysis_results_backup/lfs_stat_#106    ./analysis_results/lfs_stat_#106 
